### ISSUE TITLE
[FE] 홈페이지 스타일 추가

### ISSUE THREAD

**Issue by meanz1** [meanz1/movie-project#1]
### 🌟 설명
홈페이지 스타일 변경

### 🌳 Tasks
- [x] 스타일드 컴포넌트 사용
- [x] 페이지 제목 생성
- [x] 평점, 장르 칸 생성
- [x] 3열로 영화 카드 정렬
